name: Devo Recipes
version: v1.0.0
author: OliSickBoom
description: A txAdmin recipe for Devo Files.

tasks:
  - action: download_github
    src: https://github.com/AndreasMadsen/DevoNetwork
    subpath: server
    dest: ./.

  - action: connect_database
  - action: query_database
    file: ./sql.sql
